"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false


# Which is equivalent to
format = """
$sudo\
$username\
$hostname\
$localip\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$cmake\
$dart\
$golang\
$java\
$kotlin\
$gradle\
$lua\
$nodejs\
$python\
$rust\
$conda\
$memory_usage\
$line_break\
$jobs\
$battery\
$container\
$shell\
$character"""


right_format = """
$cmd_duration\
$time"""

[character]
format = "$symbol "
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"
vimcmd_symbol = "[â®](bold green)"
vimcmd_replace_symbol = "[â®](bold purple)"
vimcmd_visual_symbol = "[â®](bold yellow)"

[username]
format = '\[[$user]($style)\]'

[hostname]
ssh_only = true
ssh_symbol = "ğŸŒ "
style = "green dimmed bold"

[localip]
ssh_only = true
style = "yellow bold"

[directory]
truncation_length = 7
format = '\[[$path]($style)[$read_only]($read_only_style)\] '
style = "blue"
# truncation_symbol = ".../"
truncate_to_repo = false
repo_root_format = '\[[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)\] '
# ä¸‹é¢ä¸¤ä¸ªæœ‰å€¼, åœ¨gitç›®å½•ä¸‹è·¯å¾„ä¼šæ˜¾ç¤ºä¸å‡ºæ¥, æ¯”å¦‚~/.config/nvim
# before_repo_root_style = ""
# repo_root_style = ""

# [directory.substitutions]
# "Documents" = "ïœ˜ "
# "Downloads" = "ï€™ "
# "Music" = "ï¿½ "
# "Pictures" = "ï€¾ "

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = "bold green"

[git_commit]
format = '[\($hash$tag\)]($style) '
only_detached = true                # åªæœ‰ä¸€ç›´æ˜¾ç¤ºæ—¶æ‰æ˜¾ç¤ºtag
tag_disabled = false

[git_status]
format = '[($all_status )]($style)[($ahead_behind )](bold cyan)'
up_to_date = "[âœ”](bold green)"
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'

[docker_context]
format = "[$symbol$context]($style) "
symbol = "ğŸ³ "
style = "blue bold"

[package]
format = '[$symbol$version]($style) '
# symbol = "ğŸ“¦ "
symbol = "ï£– "
# symbol = "ï’‡ "
version_format = "$raw"
style = "208 bold"

[cmake]
format = "[$symbol($version )]($style)"
symbol = "â–³ "
style = "bold blue"

[dart]
format = "[$symbol($version )]($style)"
# symbol = "ğŸ¯ "
# symbol = "î™Œ"
symbol = "î˜"
style = "bold blue"

[golang]
format = "[$symbol($version )]($style)"
# symbol = "ğŸ¹ "
symbol = "î˜§ "
style = "bold cyan"

[java]
format = "[$symbol($version )]($style)"
symbol = "â˜• "
# symbol = "î‰– "
style = "red dimmed"

[kotlin]
format = "[$symbol($version )]($style)"
symbol = "ğŸ…º "
style = "bold blue"

[gradle]
format = "[$symbol($version )]($style)"
symbol = "ğŸ…¶ "
style = "bold bright-cyan"

[lua]
format = "[$symbol($version )]($style)"
# symbol = "ğŸŒ– "
symbol = "î˜  "
style = "bold blue"

[nodejs]
format = "[$symbol($version )]($style)"
symbol = "îœ˜ "
style = "bold green"

[python]
format = '[$symbol$pyenv_prefix($version )(\($virtualenv\) )]($style)'
symbol = "ğŸ "
# symbol = "îˆµ "
style = "yellow bold"

[rust]
format = '[$symbol($version )]($style)'
symbol = "ğŸ¦€ "
style = "bold red"

[conda]
format = "[$symbolenvironment](style) "
symbol = "ğŸ…’ "
style = "green bold"

[memory_usage]
format = '$symbol[$ram( | $swap)]($style) '
disabled = true
threshold = -1

[sudo]
format = "[$symbol]($style)"
disabled = false
style = "bold red"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow bold"

[time]
format = '\[[$time]($style)\]'
disabled = false
style = "cyan dimmed"


[shell]
disabled = true
style = "white bold"
